general:
  buildTool: 'maven'
  #productiveBranch: 'mavenBuildTest'
Stages:
  Build:
    mavenExecuteStaticCodeChecks: true
    npmExecuteLint: true
  'Additional Unit Tests':
     npmExecuteScripts: false 
    
